// Generated by Mason: {{feature_name}} feature
// 
// This file serves as the main entry point for the {{feature_name}} feature.
// Import this file to access all components of the feature.
//
// Usage: import 'package:your_app/app/{{feature_name}}/{{feature_name}}.dart';

export './controller/controller.dart';
export './model/model.dart';
export './view/view.dart';
export './widgets/widgets.dart';
